import jsPDF from "jspdf";
import autoTable, { type RowInput, type CellHookData } from "jspdf-autotable";
import { format } from "date-fns";
import { formatINR } from "./costCalculator";
import type { Quote, UserUsageResponse, UserUsageSummary } from "@workspace/api-client-react";

const NAVY: [number, number, number] = [14, 31, 51];
const RED: [number, number, number] = [230, 51, 41];
const SECTION_BG: [number, number, number] = [233, 237, 242];
const TOTAL_BG: [number, number, number] = [219, 225, 232];

// jsPDF's built-in fonts cannot render the ₹ glyph — strip it, keep Indian grouping.
function rs(value: number): string {
  return formatINR(value).replace(/₹/g, "").trim();
}

const fmtPct = (v: number, d = 1) => `${(v * 100).toFixed(d)}%`;

interface CB {
  steelLanded: number; scrapCost: number; recoveryCost: number; rmNet: number;
  zincCost: number; convTotal: number; protoCostPerMt: number;
  wipSteelCost: number; wipZincCost: number; financeCost: number;
  contingency: number; baseForCredit: number; creditTotal: number;
  totalBeforeMargin: number; quotePrice: number;
}

const CONV_FIELDS: [string, string][] = [
  ["Fabrication - Labour", "fabLabor"],
  ["Welding & Consumables", "weldCons"],
  ["Galvanising - Fuel & Labour", "galvFl"],
  ["Packing & Straightening", "packStrn"],
  ["Loading & Unloading", "loadUnload"],
  ["Handing Over Charge", "handover"],
  ["Others", "others"],
];

const CONT_FIELDS: [string, string][] = [
  ["Inspection + Insurance", "inspectIns"],
  ["Special Packing", "spPacking"],
  ["Freight Outward", "freightOut"],
  ["Third Party Testing", "thirdParty"],
  ["Agency Commission", "agencyComm"],
  ["BG Cost", "bgCost"],
];

const CREDIT_FIELDS: [string, string][] = [
  ["Open (Part)", "openPo"],
  ["Open (Final)", "finalPayment"],
  ["EMD", "emd"],
  ["LC", "lc"],
  ["VFS", "vfs"],
  ["ABG", "abg"],
  ["PBG", "pbg"],
  ["CPBG", "cpbg"],
  ["Advance", "advance"],
];

const MARGIN_LEVELS = [0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1];

function safeName(s: string): string {
  return s.replace(/[^A-Za-z0-9]/g, "_").replace(/_+/g, "_").slice(0, 30);
}

function duration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

function usageEventLabel(event: UserUsageSummary["recentEvents"][number]): string {
  if (event.eventType === "login") return "Signed in";
  if (event.eventType === "logout") return "Signed out";
  if (event.eventType === "page_view") return `Visited ${event.pagePath || "/"}`;
  if (event.eventType === "quote_generated") return `Generated quote #${event.entityId || "—"}`;
  if (event.eventType === "report_export") return "Downloaded quote revision PDF";
  return event.eventType;
}

function header(doc: jsPDF, title: string, left: string[], right: string[]): number {
  const pageW = doc.internal.pageSize.getWidth();
  const marginX = 40;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text(title, marginX, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(90);
  left.forEach((t, i) => doc.text(t, marginX, 64 + i * 13));
  right.forEach((t, i) => doc.text(t, pageW - marginX, 64 + i * 13, { align: "right" }));
  doc.setTextColor(0);
  return 64 + Math.max(left.length, right.length) * 13 + 6;
}

export function exportCostSheetPdf(quote: Quote): void {
  const cb = quote.costBreakdown as unknown as CB;
  const inp = quote.inputs as unknown as Record<string, number>;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const marginX = 40;

  const startY = header(
    doc,
    `Cost Analysis - ${quote.structureType}${quote.kvOption ? ` (${quote.kvOption})` : ""}`,
    [`Client: ${quote.customerName}`, `Project: ${quote.projectRef}`, `Generated By: ${quote.generatedByName}`],
    [`Date: ${format(new Date(quote.createdAt), "dd MMM yyyy")}`, `Revision: Rev ${quote.revision}`]
  );

  const body: RowInput[] = [];
  body.push(["1", "Steel", "", "", ""]);
  body.push(["", "  Steel Base Price", "", "", rs(inp.steelBasePrice)]);
  body.push(["", "  Incidental Charges", "", rs(inp.incidental || 0), ""]);
  body.push(["", "  Landed Price", "", rs(cb.steelLanded), ""]);
  body.push(["", "  Scrap", fmtPct(inp.scrapPct || 0), rs(cb.scrapCost), ""]);
  body.push(["", "  Recovery", fmtPct(inp.recoveryPct || 0), rs(cb.recoveryCost), rs(cb.rmNet)]);
  body.push(["2", "Zinc", `${inp.zincPrice} x ${(inp.zincMicron || 0).toFixed(3)}`, "", rs(cb.zincCost)]);
  body.push(["3", "Conversion", "", "", rs(cb.convTotal)]);
  for (const [lbl, k] of CONV_FIELDS) {
    const v = inp[k] || 0;
    if (v) body.push(["", "  " + lbl, "", rs(v), ""]);
  }
  if (cb.protoCostPerMt > 0) {
    body.push(["4", "Proto Fab & Assembly", `${inp.protoCost} x ${fmtPct(inp.protoPct || 0)}`, "", rs(cb.protoCostPerMt)]);
  }
  body.push(["5", "Financing", "", "", rs(cb.financeCost)]);
  body.push(["", "  WIP (Steel)", `${inp.wipSteelMonths}mo @ ${fmtPct(inp.wipSteelRate || 0, 2)}`, rs(cb.wipSteelCost), ""]);
  body.push(["", "  WIP (Zinc)", `${inp.wipZincMonths}mo @ ${fmtPct(inp.wipZincRate || 0, 2)}`, rs(cb.wipZincCost), ""]);
  body.push(["6", "Contractual", "", "", rs(cb.contingency)]);
  for (const [lbl, k] of CONT_FIELDS) {
    const v = inp[k] || 0;
    if (v) body.push(["", "  " + lbl, "", rs(v), ""]);
  }
  body.push(["", "SUBTOTAL (before credit)", "", "", rs(cb.baseForCredit)]);
  body.push(["7", "Credit Cost", "", "", rs(cb.creditTotal)]);
  for (const [lbl, k] of CREDIT_FIELDS) {
    const rate = inp[`${k}Rate`] || 0;
    const months = inp[`${k}Months`] || 0;
    const pct = inp[`${k}Pct`] || 0;
    const cost = (rate * months / 12) * pct * cb.baseForCredit;
    if (Math.abs(cost) > 0.01) {
      body.push(["", "  " + lbl, `${fmtPct(rate, 3)} x ${months}mo x ${fmtPct(pct)}`, "", rs(cost)]);
    }
  }
  body.push(["8", "TOTAL LANDED COST", "", "", rs(cb.totalBeforeMargin)]);

  autoTable(doc, {
    startY,
    head: [["#", "Section / Item", "Notes", "Sub Total", "Total (Rs/MT)"]],
    body,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 3, textColor: 30, lineColor: 222, lineWidth: 0.5 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold", halign: "left" },
    columnStyles: {
      0: { cellWidth: 22, halign: "center" },
      2: { textColor: 120 },
      3: { halign: "right" },
      4: { halign: "right" },
    },
    margin: { left: marginX, right: marginX },
    didParseCell: (d: CellHookData) => {
      if (d.section !== "body") return;
      const raw = d.row.raw as string[];
      const num = raw[0];
      const label = raw[1] || "";
      if (num && num !== "") {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.fillColor = SECTION_BG;
      }
      if (label.startsWith("SUBTOTAL") || label.startsWith("TOTAL")) {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.fillColor = TOTAL_BG;
      }
    },
  });

  // Margin scenarios
  const recPct = inp.marginPct || 0.05;
  let y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text("Margin Scenarios", marginX, y);
  y += 6;
  autoTable(doc, {
    startY: y,
    head: [["Margin %", "Margin (Rs/MT)", "Quote (Rs/MT)"]],
    body: MARGIN_LEVELS.map((m) => {
      const q = cb.totalBeforeMargin / (1 - m);
      return [fmtPct(m, 0), rs(q - cb.totalBeforeMargin), rs(q)];
    }),
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 3, lineColor: 222, lineWidth: 0.5 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    columnStyles: { 0: { halign: "center" }, 1: { halign: "right" }, 2: { halign: "right" } },
    margin: { left: marginX, right: marginX },
    tableWidth: 320,
    didParseCell: (d: CellHookData) => {
      if (d.section !== "body") return;
      // Match the dashboard rule: highlight the scenario within 0.5pp of the chosen margin.
      const label = (d.row.raw as string[])[0];
      if (Math.abs(recPct * 100 - parseInt(label, 10)) < 0.5) {
        d.cell.styles.fillColor = RED;
        d.cell.styles.textColor = 255;
        d.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Recommended quote banner
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  doc.setFillColor(...RED);
  doc.rect(marginX, y, pageW - 2 * marginX, 30, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Recommended Quote (${fmtPct(recPct, 1)} margin)`, marginX + 12, y + 19);
  doc.text(`Rs ${rs(cb.quotePrice)} /MT`, pageW - marginX - 12, y + 19, { align: "right" });
  doc.setTextColor(0);

  const stamp = format(new Date(), "yyMMdd_HHmm");
  doc.save(`CostSheet_${safeName(quote.structureType)}_Rev${quote.revision}_${stamp}.pdf`);
}

export interface RevisionReportArgs {
  customerName: string;
  projectRef: string;
  meta: string[];
  lineItemsHead: string[];
  lineItemsBody: string[][];
  /** Same shape as lineItemsBody; true marks a cell that changed from the prior revision. */
  changedMatrix: boolean[][];
  diffSections: { title: string; delta: string; rows: string[][]; note?: string }[];
}

export function exportRevisionReportPdf(args: RevisionReportArgs): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 40;

  const half = Math.ceil(args.meta.length / 2);
  const startY = header(
    doc,
    "Quote Revision Report",
    [`Client: ${args.customerName}`, `Project: ${args.projectRef}`, ...args.meta.slice(0, half)],
    args.meta.slice(half)
  );

  // Line items matrix
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text("Line Items Across Revisions", marginX, startY);
  doc.setTextColor(0);

  const revCols = args.lineItemsHead.length - 1;
  const colStyles: Record<number, { halign: "right" }> = {};
  for (let c = 1; c <= revCols; c++) colStyles[c] = { halign: "right" };

  autoTable(doc, {
    startY: startY + 6,
    head: [args.lineItemsHead],
    body: args.lineItemsBody,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 3, textColor: 30, lineColor: 222, lineWidth: 0.5 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 150 }, ...colStyles },
    margin: { left: marginX, right: marginX },
    didParseCell: (d: CellHookData) => {
      if (d.section !== "body") return;
      const raw = d.row.raw as string[];
      const ci = d.column.index;
      const label = raw[0] || "";
      if (label === "Quote Price /MT") {
        d.cell.styles.fontStyle = "bold";
        d.cell.styles.fillColor = TOTAL_BG;
      }
      // Highlight cells that changed from the prior revision (mirrors the on-screen table).
      if (ci > 0 && args.changedMatrix[d.row.index]?.[ci]) {
        d.cell.styles.textColor = RED;
        d.cell.styles.fontStyle = "bold";
      }
    },
  });

  // What changed
  let y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 22;
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text("What Changed Across Revisions", marginX, y);
  doc.setTextColor(0);
  y += 8;

  if (args.diffSections.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text("Only one revision exists - nothing to compare yet.", marginX, y + 8);
    doc.setTextColor(0);
  }

  for (const sec of args.diffSections) {
    if (y > pageH - 90) {
      doc.addPage();
      y = 50;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.text(sec.title, marginX, y + 6);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...RED);
    doc.text(sec.delta, doc.internal.pageSize.getWidth() - marginX, y + 6, { align: "right" });
    doc.setTextColor(0);
    y += 12;

    if (sec.rows.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8.5);
      doc.setTextColor(110);
      doc.text(sec.note || "No input changes - only re-saved.", marginX, y + 8);
      doc.setTextColor(0);
      y += 18;
      continue;
    }

    autoTable(doc, {
      startY: y,
      head: [["Field", "Previous", "Updated"]],
      body: sec.rows,
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3, textColor: 30, lineColor: 222, lineWidth: 0.5 },
      headStyles: { fillColor: [90, 112, 138], textColor: 255, fontStyle: "bold" },
      columnStyles: { 1: { halign: "right", textColor: 120 }, 2: { halign: "right" } },
      margin: { left: marginX, right: marginX },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 16;
  }

  const stamp = format(new Date(), "yyMMdd_HHmm");
  doc.save(`RevisionReport_${safeName(args.customerName)}_${safeName(args.projectRef)}_${stamp}.pdf`);
}

export interface UserUsageReportPdfArgs {
  data: UserUsageResponse;
  userFilterLabel: string;
}

export function exportUserUsageReportPdf({ data, userFilterLabel }: UserUsageReportPdfArgs): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const marginX = 32;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const totalSessions = data.users.reduce((sum, user) => sum + user.sessionCount, 0);
  const totalActive = data.users.reduce((sum, user) => sum + user.activeSeconds, 0);
  const totalIdle = data.users.reduce((sum, user) => sum + user.idleSeconds, 0);
  const totalPages = data.users.reduce((sum, user) => sum + user.pageVisitCount, 0);
  const totalQuotes = data.users.reduce((sum, user) => sum + user.quoteCount, 0);
  const totalCost = data.users.reduce((sum, user) => sum + user.totalCostGenerated, 0);
  const totalReports = data.users.reduce((sum, user) => sum + user.reportCount, 0);
  const rangeLabel = `${format(new Date(`${data.from}T00:00:00`), "dd MMM yyyy")} – ${format(new Date(`${data.to}T00:00:00`), "dd MMM yyyy")}`;

  let y = header(
    doc,
    "User Usage & Activity Audit",
    [`Date range: ${rangeLabel}`, `User filter: ${userFilterLabel}`],
    [`Generated: ${format(new Date(), "dd MMM yyyy, HH:mm")}`, `Users shown: ${data.users.length}`],
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text("Usage Summary", marginX, y);
  doc.setTextColor(0);

  autoTable(doc, {
    startY: y + 6,
    head: [["User", "Last active", "Sessions", "Active estimate", "Idle estimate", "Pages", "Cost sheets", "Generated cost (Rs)", "Reports"]],
    body: [
      ...data.users.map((user) => [
        `${user.userName}\n${user.email}`,
        user.lastActiveAt ? format(new Date(user.lastActiveAt), "dd MMM yyyy, HH:mm") : "No activity",
        String(user.sessionCount),
        duration(user.activeSeconds),
        duration(user.idleSeconds),
        `${user.pageVisitCount} / ${user.uniquePageCount}`,
        String(user.quoteCount),
        rs(user.totalCostGenerated),
        String(user.reportCount),
      ]),
      [
        "TOTAL",
        "",
        String(totalSessions),
        duration(totalActive),
        duration(totalIdle),
        String(totalPages),
        String(totalQuotes),
        rs(totalCost),
        String(totalReports),
      ],
    ],
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 4, textColor: 30, lineColor: 222, lineWidth: 0.5, valign: "middle" },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 150 },
      1: { cellWidth: 90 },
      2: { halign: "right", cellWidth: 48 },
      3: { halign: "right", cellWidth: 72 },
      4: { halign: "right", cellWidth: 72 },
      5: { halign: "right", cellWidth: 48 },
      6: { halign: "right", cellWidth: 58 },
      7: { halign: "right", cellWidth: 84 },
      8: { halign: "right", cellWidth: 48 },
    },
    margin: { left: marginX, right: marginX },
    // All summary columns have deliberate fixed widths (670pt total).
    // Matching that width avoids AutoTable trying to expand a non-resizable table.
    tableWidth: 670,
    didParseCell: (cell) => {
      if (cell.section === "body" && cell.row.index === data.users.length) {
        cell.cell.styles.fontStyle = "bold";
        cell.cell.styles.fillColor = TOTAL_BG;
      }
    },
  });

  doc.addPage();
  y = 46;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...NAVY);
  doc.text("Pages Visited & Recent Events", marginX, y);
  doc.setTextColor(0);
  y += 22;

  for (const user of data.users) {
    if (y > pageH - 100) {
      doc.addPage();
      y = 46;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text(`${user.userName} — ${user.email}`, marginX, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(90);
    doc.text(`${duration(user.activeSeconds)} active · ${duration(user.idleSeconds)} idle · ${user.quoteCount} cost sheets · ${user.reportCount} reports`, marginX, y + 13);
    doc.setTextColor(0);
    y += 22;

    autoTable(doc, {
      startY: y,
      head: [["Page path", "Visits", "First visited", "Last visited"]],
      body: user.pages.length
        ? user.pages.map((page) => [
            page.path,
            String(page.visits),
            page.firstVisitedAt ? format(new Date(page.firstVisitedAt), "dd MMM yyyy, HH:mm") : "—",
            page.lastVisitedAt ? format(new Date(page.lastVisitedAt), "dd MMM yyyy, HH:mm") : "—",
          ])
        : [["No page visits recorded", "", "", ""]],
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3, textColor: 30, lineColor: 222, lineWidth: 0.5 },
      headStyles: { fillColor: [90, 112, 138], textColor: 255, fontStyle: "bold" },
      columnStyles: { 0: { cellWidth: 220 }, 1: { halign: "right", cellWidth: 55 } },
      margin: { left: marginX, right: marginX },
      tableWidth: pageW - 2 * marginX,
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

    autoTable(doc, {
      startY: y,
      head: [["Recent event", "Recorded at"]],
      body: user.recentEvents.length
        ? user.recentEvents.map((event) => [usageEventLabel(event), format(new Date(event.occurredAt), "dd MMM yyyy, HH:mm")])
        : [["No usage events recorded", ""]],
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 3, textColor: 30, lineColor: 222, lineWidth: 0.5 },
      headStyles: { fillColor: [90, 112, 138], textColor: 255, fontStyle: "bold" },
      columnStyles: { 1: { halign: "right", cellWidth: 130 } },
      margin: { left: marginX, right: marginX },
      tableWidth: pageW - 2 * marginX,
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  }

  const stamp = format(new Date(), "yyMMdd_HHmm");
  doc.save(`UserUsageAudit_${data.from}_${data.to}_${safeName(userFilterLabel)}_${stamp}.pdf`);
}
