import { useState } from "react";
import {
  useGetDashboardSummary,
  useGetQuotesByStructure,
  useGetQuotesByUser,
  useListQuotes,
  type Quote,
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { formatINR } from "@/lib/costCalculator";
import { Download } from "lucide-react";
import { format } from "date-fns";
import * as XLSX from "xlsx";

function exportQuotesToExcel(quotes: Quote[] | undefined) {
  if (!quotes || quotes.length === 0) return;

  const rows = quotes.map((q) => ({
    Date: format(new Date(q.createdAt), "dd MMM yyyy HH:mm"),
    Customer: q.customerName,
    "Project / PO Ref": q.projectRef,
    Revision: `Rev ${q.revision}`,
    "Structure Type": q.structureType,
    "kV Option": q.kvOption ?? "",
    "Quote Price / MT (₹)": q.quotePricePerMt ? Number(q.quotePricePerMt) : "",
    "Total Cost (₹)": q.totalCost ? Number(q.totalCost) : "",
    "Steel Base Price (₹)": q.steelPrice ? Number(q.steelPrice) : "",
    "Zinc Price (₹)": q.zincPrice ? Number(q.zincPrice) : "",
    "Generated By": q.generatedByName,
  }));

  const ws = XLSX.utils.json_to_sheet(rows);

  // Column widths
  ws["!cols"] = [
    { wch: 18 }, // Date
    { wch: 32 }, // Customer
    { wch: 20 }, // Project Ref
    { wch: 10 }, // Revision
    { wch: 28 }, // Structure Type
    { wch: 10 }, // kV Option
    { wch: 22 }, // Quote Price
    { wch: 20 }, // Total Cost
    { wch: 22 }, // Steel Base
    { wch: 18 }, // Zinc Price
    { wch: 18 }, // Generated By
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Quotes");

  // Summary sheet
  const summaryRows = [
    ["Vijay Transmission — Cost Sheet Export"],
    ["Exported on", format(new Date(), "dd MMM yyyy HH:mm")],
    ["Total records", quotes.length],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [{ wch: 24 }, { wch: 24 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Info");

  const filename = `VT_Quotes_${format(new Date(), "yyyyMMdd_HHmm")}.xlsx`;
  XLSX.writeFile(wb, filename);
}

export default function Dashboard() {
  const { data: summary } = useGetDashboardSummary();
  const { data: structureData } = useGetQuotesByStructure();
  const { data: userData } = useGetQuotesByUser();
  const { data: allQuotes, isLoading: loadingQuotes } = useListQuotes();
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      exportQuotesToExcel(allQuotes);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-muted-foreground">Overview of all quoting activity</p>
        </div>
        <Button
          variant="outline"
          onClick={handleExport}
          disabled={exporting || loadingQuotes || !allQuotes?.length}
          className="gap-2"
          data-testid="button-export-excel"
        >
          <Download className="h-4 w-4" />
          {exporting
            ? "Exporting…"
            : loadingQuotes
            ? "Loading…"
            : `Export to Excel (${allQuotes?.length ?? 0})`}
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Quotes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-mono">{summary?.totalQuotes || 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Customers</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-mono">{summary?.totalCustomers || 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Quotes This Month</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-mono">{summary?.quotesThisMonth || 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Avg Quote Price</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-mono text-primary">
              {formatINR(summary?.avgQuotePrice || 0)}
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>Quotes by Structure Type</CardTitle>
          </CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={structureData || []}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.2} vertical={false} />
                <XAxis dataKey="structureType" tick={{ fontSize: 12 }} />
                <YAxis tick={{ fontSize: 12 }} />
                <Tooltip
                  cursor={{ fill: "rgba(255,255,255,0.1)" }}
                  contentStyle={{ backgroundColor: "var(--popover)", borderColor: "var(--border)" }}
                />
                <Bar dataKey="count" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="col-span-1">
          <CardHeader>
            <CardTitle>Quotes by User</CardTitle>
          </CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={userData || []} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" opacity={0.2} horizontal={false} />
                <XAxis type="number" tick={{ fontSize: 12 }} />
                <YAxis dataKey="userName" type="category" tick={{ fontSize: 12 }} width={100} />
                <Tooltip
                  cursor={{ fill: "rgba(255,255,255,0.1)" }}
                  contentStyle={{ backgroundColor: "var(--popover)", borderColor: "var(--border)" }}
                />
                <Bar dataKey="count" fill="hsl(var(--accent))" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
