import { useMemo } from "react";
import { useSearch, useLocation } from "wouter";
import {
  useGetQuote,
  useListQuotes,
  getGetQuoteQueryKey,
  getListQuotesQueryKey,
  type Quote,
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, PieChart, Pie, Cell, Legend,
} from "recharts";
import { formatINR } from "@/lib/costCalculator";
import { Download, FileBarChart, Plus, History, FileText } from "lucide-react";
import { exportCostSheetPdf } from "@/lib/pdfExport";
import { format } from "date-fns";
import * as XLSX from "xlsx";

// ---- Palette (matching HTML reference) ----
const PALETTE = {
  accent:  "#e63329",
  accent2: "#ff6a3c",
  steel:   "#3d6ea5",
  steelLt: "#6f9bd1",
  mist:    "#aebccd",
  slate:   "#5b708a",
  ok:      "#34d399",
  gridline:"rgba(174,188,205,.12)",
  txt:     "#aebccd",
};

const DONUT_COLORS = [
  PALETTE.accent, PALETTE.accent2, PALETTE.steel,
  PALETTE.steelLt, PALETTE.ok, PALETTE.slate, PALETTE.mist,
];

const MARGIN_LEVELS = [0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.10];

interface CB {
  steelLanded: number; scrapCost: number; recoveryCost: number; rmNet: number;
  zincCost: number; convTotal: number; protoCostPerMt: number;
  wipSteelCost: number; wipZincCost: number; financeCost: number;
  contingency: number; baseForCredit: number; creditTotal: number;
  totalBeforeMargin: number; quotePrice: number;
}

function getBreakdownSections(cb: CB) {
  return [
    { name: "RM Net", value: cb.rmNet },
    { name: "Zinc", value: cb.zincCost },
    { name: "Conversion", value: cb.convTotal },
    { name: "Proto", value: cb.protoCostPerMt },
    { name: "Finance", value: cb.financeCost },
    { name: "Contingency", value: cb.contingency },
    { name: "Credit", value: cb.creditTotal },
  ].filter(s => s.value > 0.01);
}

function getMarginScenarios(totalBeforeMargin: number) {
  return MARGIN_LEVELS.map(m => ({
    label: `${(m * 100).toFixed(0)}%`,
    cost: Math.round(totalBeforeMargin),
    quote: Math.round(totalBeforeMargin / (1 - m)),
  }));
}

// ---- Export (mirrors HTML reference format exactly) ----
function exportCostSheet(quote: Quote) {
  const cb = quote.costBreakdown as unknown as CB;
  const inp = quote.inputs as unknown as Record<string, number>;
  const fmtPct = (v: number, d = 1) => `${(v * 100).toFixed(d)}%`;

  const aoa: (string | number)[][] = [];
  aoa.push([`COST ANALYSIS — ${quote.structureType}${quote.kvOption ? " (" + quote.kvOption + ")" : ""}`]);
  aoa.push([]);
  aoa.push(["Client:", quote.customerName, "", "Date:", format(new Date(quote.createdAt), "dd MMM yyyy")]);
  aoa.push(["Project:", quote.projectRef, "", "Rev:", `Rev ${quote.revision}`]);
  aoa.push(["Generated By:", quote.generatedByName]);
  aoa.push([]);
  aoa.push(["#", "Section / Item", "Notes", "Sub Total", "Total (₹/MT)"]);

  // Steel
  aoa.push(["1", "Steel"]);
  aoa.push(["", "  Steel Base Price", "", "", inp.steelBasePrice]);
  aoa.push(["", "  Incidental Charges", "", inp.incidental || 0, ""]);
  aoa.push(["", "  Landed Price", "", cb.steelLanded, ""]);
  aoa.push(["", "  Scrap", fmtPct(inp.scrapPct || 0), cb.scrapCost, ""]);
  aoa.push(["", "  Recovery", fmtPct(inp.recoveryPct || 0), cb.recoveryCost, cb.rmNet]);

  // Zinc
  aoa.push(["2", "Zinc", `${inp.zincPrice} × ${fmtPct(inp.zincMicron || 0, 3)}`, "", cb.zincCost]);

  // Conversion
  aoa.push(["3", "Conversion", "", "", cb.convTotal]);
  const convFields: [string, string][] = [
    ["Fabrication – Labour", "fabLabor"],
    ["Welding & Consumables", "weldCons"],
    ["Galvanising – Fuel & Labour", "galvFl"],
    ["Packing & Straightening", "packStrn"],
    ["Loading & Unloading", "loadUnload"],
    ["Handing Over Charge", "handover"],
    ["Others", "others"],
  ];
  for (const [lbl, k] of convFields) {
    const v = inp[k] || 0;
    if (v) aoa.push(["", "  " + lbl, "", v, ""]);
  }

  // Proto
  if (cb.protoCostPerMt > 0) {
    aoa.push(["4", "Proto Fab & Assembly",
      `${inp.protoCost} × ${fmtPct(inp.protoPct || 0)}`, "", cb.protoCostPerMt]);
  }

  // Financing
  aoa.push(["5", "Financing", "", "", cb.financeCost]);
  aoa.push(["", "  WIP (Steel)",
    `${inp.wipSteelMonths}mo @ ${fmtPct(inp.wipSteelRate || 0, 2)}`, cb.wipSteelCost, ""]);
  aoa.push(["", "  WIP (Zinc)",
    `${inp.wipZincMonths}mo @ ${fmtPct(inp.wipZincRate || 0, 2)}`, cb.wipZincCost, ""]);

  // Contractual
  aoa.push(["6", "Contractual", "", "", cb.contingency]);
  const contFields: [string, string][] = [
    ["Inspection + Insurance", "inspectIns"],
    ["Special Packing", "spPacking"],
    ["Freight Outward", "freightOut"],
    ["Third Party Testing", "thirdParty"],
    ["Agency Commission", "agencyComm"],
    ["BG Cost", "bgCost"],
  ];
  for (const [lbl, k] of contFields) {
    const v = inp[k] || 0;
    if (v) aoa.push(["", "  " + lbl, "", v, ""]);
  }

  aoa.push(["", "SUBTOTAL (before credit)", "", "", cb.baseForCredit]);

  // Credit Cost
  aoa.push(["7", "Credit Cost", "", "", cb.creditTotal]);
  const creditFields: [string, string][] = [
    ["Open (Part)", "openPo"],
    ["Open (Final)", "finalPayment"],
    ["EMD", "emd"],
    ["LC", "lc"],
    ["VFS", "vfs"],
    ["ABG", "abg"],
    ["PBG", "pbg"],
    ["CPBG", "cpbg"],
    ["Advance", "advance"],
  ];
  for (const [lbl, k] of creditFields) {
    const rate = inp[`${k}Rate`] || 0;
    const months = inp[`${k}Months`] || 0;
    const pct = inp[`${k}Pct`] || 0;
    const cost = (rate * months / 12) * pct * cb.baseForCredit;
    if (Math.abs(cost) > 0.01)
      aoa.push(["", "  " + lbl,
        `${fmtPct(rate, 3)} × ${months}mo × ${fmtPct(pct)}`, "", cost]);
  }

  aoa.push(["8", "TOTAL LANDED COST", "", "", cb.totalBeforeMargin]);
  aoa.push([]);
  aoa.push(["9", "Margin scenarios"]);
  aoa.push(["", "Margin %", "Margin (₹/MT)", "Quote (₹/MT)"]);
  for (const m of MARGIN_LEVELS) {
    const q = cb.totalBeforeMargin / (1 - m);
    aoa.push(["", fmtPct(m, 1), q - cb.totalBeforeMargin, q]);
  }
  aoa.push([]);
  const recPct = inp.marginPct || 0.05;
  const recQuote = cb.quotePrice;
  aoa.push(["10", "RECOMMENDED QUOTE",
    `${fmtPct(recPct, 1)} margin`, recQuote + " /MT", recQuote]);

  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!cols"] = [{ wch: 4 }, { wch: 36 }, { wch: 30 }, { wch: 14 }, { wch: 16 }];
  // Number format all numeric cells
  for (const addr in ws) {
    if (addr.startsWith("!")) continue;
    const cell = ws[addr];
    if (typeof cell.v === "number") cell.z = "#,##0";
  }

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Cost Analysis");

  // Inputs snapshot sheet
  const inpAoa: (string | number)[][] = [
    ["INPUT SNAPSHOT"], [],
    ["Structure", quote.structureType],
    ["kV Option", quote.kvOption || ""],
    ["Client", quote.customerName],
    ["Project", quote.projectRef],
    ["Date generated", format(new Date(quote.createdAt), "dd MMM yyyy")],
    [],
    ["Parameter", "Value"],
  ];
  for (const [k, v] of Object.entries(inp)) {
    inpAoa.push([k, typeof v === "number" ? v : String(v)]);
  }
  const wsIn = XLSX.utils.aoa_to_sheet(inpAoa);
  wsIn["!cols"] = [{ wch: 28 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, wsIn, "Inputs");

  const stamp = format(new Date(), "yyMMdd_HHmm");
  const safe = quote.structureType.replace(/[^A-Za-z0-9]/g, "_").replace(/_+/g, "_").slice(0, 30);
  XLSX.writeFile(wb, `CostSheet_${safe}_${stamp}.xlsx`);
}

// ---- Tooltip styles ----
const tooltipStyle = { backgroundColor: "#0e1f33", borderColor: "#2a3f57", color: "#aebccd" };

// ---- Empty state ----
function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-24 gap-4 text-center">
      <FileBarChart className="h-14 w-14 text-muted-foreground/30" />
      <div>
        <p className="text-lg font-semibold">No quote loaded</p>
        <p className="text-sm text-muted-foreground mt-1">
          Save a quote from the Calculator to see the full cost breakdown here.
        </p>
      </div>
    </div>
  );
}

// ---- KPI Card ----
function KpiCard({
  label, value, unit, sub, accent = false,
}: { label: string; value: string; unit?: string; sub?: string; accent?: boolean }) {
  return (
    <div className={`relative overflow-hidden rounded-xl border p-5 ${
      accent
        ? "bg-gradient-to-br from-primary/16 to-primary/5 border-primary/30"
        : "bg-gradient-to-br from-card to-card/70 border-border/60"
    }`}>
      <div className="absolute top-0 left-0 w-full h-[3px] bg-gradient-to-r from-primary via-accent2 to-transparent opacity-70" />
      <div className="text-[10px] tracking-[0.14em] uppercase font-mono text-muted-foreground mb-2">{label}</div>
      <div className="flex items-baseline gap-1.5">
        <span className="text-[26px] font-mono font-bold leading-none text-foreground">{value}</span>
        {unit && <span className="text-xs font-mono text-muted-foreground">{unit}</span>}
      </div>
      {sub && <div className="mt-1.5 text-[10.5px] font-mono text-muted-foreground">{sub}</div>}
    </div>
  );
}

// ---- Main Component ----
export default function Dashboard() {
  const search = useSearch();
  const [, setLocation] = useLocation();
  const params = new URLSearchParams(search);
  const idParam = params.get("id");
  const quoteId = idParam ? parseInt(idParam, 10) : undefined;

  // If we have a specific quote ID, load it; otherwise load the most recent
  const { data: specificQuote, isLoading: loadingSpecific } = useGetQuote(
    quoteId ?? 0,
    { query: { enabled: !!quoteId, queryKey: getGetQuoteQueryKey(quoteId ?? 0) } }
  );
  const { data: allQuotes, isLoading: loadingAll } = useListQuotes(
    undefined,
    { query: { enabled: !quoteId, queryKey: getListQuotesQueryKey() } }
  );

  const isLoading = quoteId ? loadingSpecific : loadingAll;
  const quote: Quote | undefined = quoteId
    ? specificQuote
    : allQuotes?.[0]; // listQuotes returns most-recent first

  const cb = quote?.costBreakdown as unknown as CB | undefined;
  const inp = quote?.inputs as unknown as Record<string, number> | undefined;

  const sections = useMemo(() => cb ? getBreakdownSections(cb) : [], [cb]);
  const marginScenarios = useMemo(() => cb ? getMarginScenarios(cb.totalBeforeMargin) : [], [cb]);
  const recPct = inp?.marginPct ?? 0.05;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-24 text-muted-foreground text-sm animate-pulse">
        Loading dashboard…
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500 max-w-6xl mx-auto pb-10">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Quote Dashboard</h1>
          {quote ? (
            <div className="text-muted-foreground text-sm mt-0.5 flex flex-wrap items-center gap-x-1">
              <span className="font-medium text-foreground">{quote.structureType}</span>
              {quote.kvOption && <span className="text-muted-foreground"> ({quote.kvOption})</span>}
              {" · "}<span>{quote.customerName}</span>
              {" · "}<span className="font-mono">{quote.projectRef}</span>
              {" · "}<Badge variant="outline" className="font-mono text-xs ml-0.5">Rev {quote.revision}</Badge>
            </div>
          ) : (
            <p className="text-muted-foreground text-sm">Visualise cost breakdown, margins and export the cost sheet</p>
          )}
        </div>
        {quote && cb && (
          <div className="flex gap-2 shrink-0">
            <Button
              variant="outline"
              onClick={() => exportCostSheetPdf(quote)}
              className="gap-2"
              data-testid="button-export-pdf"
            >
              <FileText className="h-4 w-4" />
              Download PDF
            </Button>
            <Button
              variant="outline"
              onClick={() => exportCostSheet(quote)}
              className="gap-2"
              data-testid="button-export-excel"
            >
              <Download className="h-4 w-4" />
              Export .xlsx
            </Button>
          </div>
        )}
      </div>

      {!quote ? (
        <EmptyState />
      ) : cb ? (
        <>
          {/* KPIs */}
          <div className="grid gap-4 grid-cols-2 md:grid-cols-4">
            <KpiCard
              label="Landed Cost"
              value={formatINR(cb.totalBeforeMargin)}
              unit="/MT"
              sub="all-in, pre-margin"
            />
            <KpiCard
              label="Subtotal"
              value={formatINR(cb.baseForCredit)}
              unit="/MT"
              sub="before credit cost"
            />
            <KpiCard
              label={`Quote @ ${(recPct * 100).toFixed(1)}%`}
              value={formatINR(cb.quotePrice)}
              unit="/MT"
              sub="recommended"
              accent
            />
            <KpiCard
              label="Margin Applied"
              value={`${(recPct * 100).toFixed(1)}%`}
              sub={`+${formatINR(cb.quotePrice - cb.totalBeforeMargin)} /MT`}
            />
          </div>

          {/* Charts row 1: Build-up + Donut */}
          <div className="grid gap-4 md:grid-cols-[1.4fr_1fr]">
            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-[15px]">Cost Build-up</CardTitle>
                <p className="text-xs text-muted-foreground">Component breakdown per MT</p>
              </CardHeader>
              <CardContent className="h-[340px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={sections} margin={{ top: 4, right: 16, left: 0, bottom: 4 }}>
                    <CartesianGrid strokeDasharray="3 3" opacity={0.15} vertical={false} />
                    <XAxis
                      dataKey="name"
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                    />
                    <YAxis
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                      tickFormatter={(v) => `₹${(v/1000).toFixed(0)}k`}
                    />
                    <Tooltip
                      contentStyle={tooltipStyle}
                      cursor={{ fill: "rgba(255,255,255,0.05)" }}
                      formatter={(v: number) => [formatINR(v), "₹/MT"]}
                    />
                    <Bar
                      dataKey="value"
                      radius={[6, 6, 0, 0]}
                      maxBarSize={46}
                    >
                      {sections.map((s, i) => (
                        <Cell key={s.name} fill={i === 0 ? PALETTE.accent : PALETTE.steel} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-[15px]">Composition</CardTitle>
                <p className="text-xs text-muted-foreground">Cost mix by component</p>
              </CardHeader>
              <CardContent className="h-[340px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={sections}
                      dataKey="value"
                      nameKey="name"
                      cx="45%"
                      cy="50%"
                      innerRadius="52%"
                      outerRadius="78%"
                    >
                      {sections.map((s, i) => (
                        <Cell key={s.name} fill={DONUT_COLORS[i % DONUT_COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip
                      contentStyle={tooltipStyle}
                      formatter={(v: number) => [formatINR(v), "₹/MT"]}
                    />
                    <Legend
                      layout="vertical"
                      align="right"
                      verticalAlign="middle"
                      iconType="circle"
                      iconSize={10}
                      formatter={(v) => (
                        <span style={{ color: PALETTE.txt, fontFamily: "Sora", fontSize: 11.5 }}>{v}</span>
                      )}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          {/* Charts row 2: Margin scenarios + Cost drivers */}
          <div className="grid gap-4 md:grid-cols-2">
            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-[15px]">Margin Scenarios</CardTitle>
                <p className="text-xs text-muted-foreground">Cost vs quote price at different margins</p>
              </CardHeader>
              <CardContent className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={marginScenarios} margin={{ top: 4, right: 16, left: 0, bottom: 4 }}>
                    <CartesianGrid strokeDasharray="3 3" opacity={0.15} vertical={false} />
                    <XAxis
                      dataKey="label"
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                    />
                    <YAxis
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                      tickFormatter={(v) => `₹${(v/1000).toFixed(0)}k`}
                    />
                    <Tooltip
                      contentStyle={tooltipStyle}
                      cursor={{ fill: "rgba(255,255,255,0.05)" }}
                      formatter={(v: number) => [formatINR(v), ""]}
                    />
                    <Legend formatter={(v) => (
                      <span style={{ color: PALETTE.txt, fontFamily: "Sora", fontSize: 12 }}>{v}</span>
                    )} />
                    <Bar dataKey="cost" name="Cost (₹/MT)" fill={PALETTE.slate} radius={[5, 5, 0, 0]} maxBarSize={40} />
                    <Bar dataKey="quote" name="Quote (₹/MT)" fill={PALETTE.accent} radius={[5, 5, 0, 0]} maxBarSize={40} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="text-[15px]">Cost Drivers</CardTitle>
                <p className="text-xs text-muted-foreground">₹/MT contribution by section</p>
              </CardHeader>
              <CardContent className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={[...sections].sort((a, b) => b.value - a.value)}
                    layout="vertical"
                    margin={{ top: 4, right: 16, left: 0, bottom: 4 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" opacity={0.15} horizontal={false} />
                    <XAxis
                      type="number"
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                      tickFormatter={(v) => `₹${(v/1000).toFixed(0)}k`}
                    />
                    <YAxis
                      dataKey="name"
                      type="category"
                      tick={{ fill: PALETTE.slate, fontFamily: "Space Mono", fontSize: 10 }}
                      axisLine={false} tickLine={false}
                      width={76}
                    />
                    <Tooltip
                      contentStyle={tooltipStyle}
                      cursor={{ fill: "rgba(255,255,255,0.05)" }}
                      formatter={(v: number) => [formatINR(v), "₹/MT"]}
                    />
                    <Bar dataKey="value" fill={PALETTE.accent2} radius={[0, 5, 5, 0]} maxBarSize={40} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          {/* Cost Sheet Table */}
          <Card className="border-border/50 overflow-hidden">
            <CardHeader className="bg-card/50 border-b border-border/50 pb-3">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-[15px]">Full Cost Sheet</CardTitle>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {quote.structureType} · {quote.customerName} · {quote.projectRef} · {format(new Date(quote.createdAt), "dd MMM yyyy")}
                  </p>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border/50 bg-muted/30">
                    <th className="text-left px-4 py-2.5 text-muted-foreground font-medium w-8">#</th>
                    <th className="text-left px-4 py-2.5 text-muted-foreground font-medium">Section / Item</th>
                    <th className="text-right px-4 py-2.5 text-muted-foreground font-medium font-mono">Sub Total</th>
                    <th className="text-right px-4 py-2.5 text-muted-foreground font-medium font-mono">Total (₹/MT)</th>
                  </tr>
                </thead>
                <tbody>
                  <CostRow n="1" label="Steel" total={formatINR(cb.rmNet)} section />
                  <CostRow label="Steel Base Price" sub={formatINR(inp?.steelBasePrice ?? 0)} />
                  <CostRow label="Incidental Charges" sub={formatINR(inp?.incidental ?? 0)} />
                  <CostRow label="Scrap" sub={formatINR(cb.scrapCost)} />
                  <CostRow label="Recovery" sub={formatINR(cb.recoveryCost)} />

                  <CostRow n="2" label="Zinc" total={formatINR(cb.zincCost)} section />
                  <CostRow label={`Zinc Price × Micron (${((inp?.zincMicron ?? 0) * 100).toFixed(2)}%)`}
                    sub={formatINR(cb.zincCost)} />

                  <CostRow n="3" label="Conversion" total={formatINR(cb.convTotal)} section />
                  {(inp?.fabLabor ?? 0) > 0 && <CostRow label="Fabrication – Labour" sub={formatINR(inp!.fabLabor)} />}
                  {(inp?.weldCons ?? 0) > 0 && <CostRow label="Welding & Consumables" sub={formatINR(inp!.weldCons)} />}
                  {(inp?.galvFl ?? 0) > 0 && <CostRow label="Galvanising – Fuel & Labour" sub={formatINR(inp!.galvFl)} />}
                  {(inp?.packStrn ?? 0) > 0 && <CostRow label="Packing & Straightening" sub={formatINR(inp!.packStrn)} />}
                  {(inp?.loadUnload ?? 0) > 0 && <CostRow label="Loading & Unloading" sub={formatINR(inp!.loadUnload)} />}
                  {(inp?.handover ?? 0) > 0 && <CostRow label="Handing Over Charge" sub={formatINR(inp!.handover)} />}
                  {(inp?.others ?? 0) > 0 && <CostRow label="Others" sub={formatINR(inp!.others)} />}

                  {cb.protoCostPerMt > 0 && (
                    <CostRow n="4" label="Proto Fab & Assembly" total={formatINR(cb.protoCostPerMt)} section />
                  )}

                  <CostRow n="5" label="Financing" total={formatINR(cb.financeCost)} section />
                  <CostRow label={`WIP – Steel (${inp?.wipSteelMonths ?? 0}mo @ ${((inp?.wipSteelRate ?? 0)*100).toFixed(2)}%)`}
                    sub={formatINR(cb.wipSteelCost)} />
                  <CostRow label={`WIP – Zinc (${inp?.wipZincMonths ?? 0}mo @ ${((inp?.wipZincRate ?? 0)*100).toFixed(2)}%)`}
                    sub={formatINR(cb.wipZincCost)} />

                  <CostRow n="6" label="Contractual" total={formatINR(cb.contingency)} section />
                  {(inp?.inspectIns ?? 0) > 0 && <CostRow label="Inspection + Insurance" sub={formatINR(inp!.inspectIns)} />}
                  {(inp?.spPacking ?? 0) > 0 && <CostRow label="Special Packing" sub={formatINR(inp!.spPacking)} />}
                  {(inp?.freightOut ?? 0) > 0 && <CostRow label="Freight Outward" sub={formatINR(inp!.freightOut)} />}
                  {(inp?.thirdParty ?? 0) > 0 && <CostRow label="Third Party Testing" sub={formatINR(inp!.thirdParty)} />}
                  {(inp?.agencyComm ?? 0) > 0 && <CostRow label="Agency Commission" sub={formatINR(inp!.agencyComm)} />}
                  {(inp?.bgCost ?? 0) > 0 && <CostRow label="BG Cost" sub={formatINR(inp!.bgCost)} />}

                  <tr className="border-y border-border/80 bg-muted/40">
                    <td className="px-4 py-2.5" />
                    <td className="px-4 py-2.5 font-bold text-sm" colSpan={2}>Subtotal (before credit)</td>
                    <td className="px-4 py-2.5 text-right font-mono font-bold">{formatINR(cb.baseForCredit)}</td>
                  </tr>

                  <CostRow n="7" label="Credit Cost" total={formatINR(cb.creditTotal)} section />

                  <tr className="border-y-2 border-primary/30 bg-primary/5">
                    <td className="px-4 py-3" />
                    <td className="px-4 py-3 font-bold" colSpan={2}>Total Landed Cost (8)</td>
                    <td className="px-4 py-3 text-right font-mono font-bold text-lg text-primary">{formatINR(cb.totalBeforeMargin)}</td>
                  </tr>

                  <tr className="bg-muted/20 border-b border-border/50">
                    <td className="px-4 py-2.5 font-medium text-muted-foreground">9</td>
                    <td className="px-4 py-2.5 font-bold" colSpan={3}>Margin Scenarios</td>
                  </tr>
                  <tr className="border-b border-border/30 bg-muted/10">
                    <td />
                    <td className="px-4 py-1.5 text-xs text-muted-foreground font-medium">Margin %</td>
                    <td className="px-4 py-1.5 text-right text-xs text-muted-foreground font-medium font-mono">Margin (₹/MT)</td>
                    <td className="px-4 py-1.5 text-right text-xs text-muted-foreground font-medium font-mono">Quote (₹/MT)</td>
                  </tr>
                  {marginScenarios.map((m) => {
                    const isRec = Math.abs((recPct * 100) - parseInt(m.label)) < 0.5;
                    return (
                      <tr key={m.label} className={`border-b border-border/20 ${isRec ? "bg-primary/5" : ""}`}>
                        <td />
                        <td className={`px-4 py-1.5 font-mono text-sm ${isRec ? "text-primary font-bold" : "text-muted-foreground"}`}>
                          {m.label}
                        </td>
                        <td className={`px-4 py-1.5 text-right font-mono text-sm ${isRec ? "text-primary" : "text-muted-foreground"}`}>
                          {formatINR(m.quote - m.cost)}
                        </td>
                        <td className={`px-4 py-1.5 text-right font-mono font-bold text-sm ${isRec ? "text-primary" : ""}`}>
                          {formatINR(m.quote)}
                        </td>
                      </tr>
                    );
                  })}

                  <tr className="border-t-2 border-primary bg-primary/10">
                    <td />
                    <td className="px-4 py-3 font-bold text-primary" colSpan={2}>
                      Recommended Quote (Ex Works, {(recPct * 100).toFixed(1)}% margin)
                    </td>
                    <td className="px-4 py-3 text-right font-mono font-bold text-primary text-lg">
                      {formatINR(cb.quotePrice)} /MT
                    </td>
                  </tr>
                </tbody>
              </table>
            </CardContent>
          </Card>

          {/* Bottom navigation */}
          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <Button
              onClick={() => setLocation("/rm-prices")}
              className="gap-2 font-bold"
              data-testid="button-start-new"
            >
              <Plus className="h-4 w-4" />
              Start New
            </Button>
            {quote.revision >= 1 && (
              <Button
                variant="outline"
                onClick={() =>
                  setLocation(
                    `/review?customerId=${quote.customerId}&project=${encodeURIComponent(quote.projectRef)}`
                  )
                }
                className="gap-2"
                data-testid="button-review-earlier"
              >
                <History className="h-4 w-4" />
                Review Earlier Quotes
              </Button>
            )}
          </div>
        </>
      ) : (
        <EmptyState />
      )}
    </div>
  );
}

function CostRow({
  n, label, sub, total, section = false,
}: {
  n?: string; label: string; sub?: string; total?: string; section?: boolean;
}) {
  if (section) {
    return (
      <tr className="border-b border-border/40 bg-card/60">
        <td className="px-4 py-2.5 font-medium text-muted-foreground text-xs">{n}</td>
        <td className="px-4 py-2.5 font-bold text-sm" colSpan={sub ? 1 : 2}>{label}</td>
        {sub && <td className="px-4 py-2.5 text-right font-mono text-sm">{sub}</td>}
        <td className="px-4 py-2.5 text-right font-mono font-bold text-sm">{total}</td>
      </tr>
    );
  }
  return (
    <tr className="border-b border-border/20 hover:bg-accent/5">
      <td className="px-4 py-2" />
      <td className="px-4 py-2 text-sm text-muted-foreground pl-8">{label}</td>
      <td className="px-4 py-2 text-right font-mono text-sm text-muted-foreground">{sub}</td>
      <td className="px-4 py-2 text-right font-mono text-sm">{total}</td>
    </tr>
  );
}
