import { useState } from "react";
import { useListCustomers, useGetProjectsByCustomer, useGetQuotesByProject } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
import { formatINR } from "@/lib/costCalculator";

export default function Review() {
  const [selectedCustomerId, setSelectedCustomerId] = useState<string>("");
  const [selectedProject, setSelectedProject] = useState<string>("");

  const { data: customers, isLoading: loadingCustomers } = useListCustomers();
  
  const customerId = selectedCustomerId ? parseInt(selectedCustomerId, 10) : 0;
  
  const { data: projects } = useGetProjectsByCustomer(
    { customerId },
    {
      query: {
        enabled: !!customerId,
        queryKey: ["projects", customerId]
      }
    }
  );

  const { data: quotes, isLoading: loadingQuotes } = useGetQuotesByProject(
    { customerId, projectRef: selectedProject },
    {
      query: {
        enabled: !!customerId && !!selectedProject,
        queryKey: ["quotes", customerId, selectedProject]
      }
    }
  );

  return (
    <div className="space-y-6 animate-in fade-in duration-500 max-w-6xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Review Quotes</h1>
          <p className="text-muted-foreground">Compare quote revisions by project</p>
        </div>
      </div>

      <Card className="border-border/50">
        <CardHeader className="bg-card/50 pb-4 border-b border-border/50">
          <CardTitle className="text-lg">Select Project</CardTitle>
          <CardDescription>Choose a customer and project reference to view history.</CardDescription>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="grid gap-6 md:grid-cols-2 max-w-2xl">
            <div className="space-y-2">
              <Label>Customer</Label>
              <Select value={selectedCustomerId} onValueChange={(val) => { setSelectedCustomerId(val); setSelectedProject(""); }}>
                <SelectTrigger>
                  <SelectValue placeholder={loadingCustomers ? "Loading..." : "Select customer"} />
                </SelectTrigger>
                <SelectContent>
                  {customers?.map(c => (
                    <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label>Project / PO Ref</Label>
              <Select value={selectedProject} onValueChange={setSelectedProject} disabled={!selectedCustomerId || projects?.length === 0}>
                <SelectTrigger>
                  <SelectValue placeholder={!selectedCustomerId ? "Select customer first" : projects?.length === 0 ? "No projects found" : "Select project"} />
                </SelectTrigger>
                <SelectContent>
                  {projects?.map(p => (
                    <SelectItem key={p} value={p}>{p}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {customerId && selectedProject && (
        <Card className="border-border/50 overflow-hidden">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader className="bg-card/50">
                <TableRow>
                  <TableHead>Rev</TableHead>
                  <TableHead>Structure</TableHead>
                  <TableHead className="text-right">Quote Price / MT</TableHead>
                  <TableHead className="text-right">Steel Base</TableHead>
                  <TableHead className="text-right">Zinc Price</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Date</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loadingQuotes ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">Loading quotes...</TableCell>
                  </TableRow>
                ) : quotes?.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">No quotes found for this project.</TableCell>
                  </TableRow>
                ) : (
                  quotes?.map((quote) => (
                    <TableRow key={quote.id} className="hover:bg-accent/5">
                      <TableCell>
                        <Badge variant="outline" className="font-mono bg-card">Rev {quote.revision}</Badge>
                      </TableCell>
                      <TableCell>
                        <div className="font-medium">{quote.structureType}</div>
                        {quote.kvOption && <div className="text-xs text-muted-foreground">{quote.kvOption}</div>}
                      </TableCell>
                      <TableCell className="text-right font-mono font-bold text-primary">
                        {formatINR(quote.quotePricePerMt)}
                      </TableCell>
                      <TableCell className="text-right font-mono text-muted-foreground">
                        {quote.steelPrice ? formatINR(quote.steelPrice) : "-"}
                      </TableCell>
                      <TableCell className="text-right font-mono text-muted-foreground">
                        {quote.zincPrice ? formatINR(quote.zincPrice) : "-"}
                      </TableCell>
                      <TableCell className="text-sm">{quote.generatedByName}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {format(new Date(quote.createdAt), 'dd MMM yyyy, HH:mm')}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </Card>
      )}
    </div>
  );
}
